In [2]:
import numpy as np

# Matrices

- 1d arrays can think of as vectors and 2d arrays as matrices
- numpy.matrix is not recommended


representing matrix not using numpy

In [3]:
L = [[1,2], [3,4]]
L

[[1, 2], [3, 4]]

In [4]:
L[0] #get row

[1, 2]

In [5]:
L[0][1] #get col

2

using numpy

In [6]:
A = np.array([[1,2], [3,4]])
A

array([[1, 2],
       [3, 4]])

Selecting matrix elements in numpy

In [7]:
A[0][1] #list style

2

In [8]:
A[0,1] #numpy style

2

Selecting a column

In [9]:
A[:,0]#: means select everything in this dimension

array([1, 3])

In [10]:
A.T #transpose

array([[1, 3],
       [2, 4]])

Functions are applied elementwise

In [11]:
np.exp(A)

array([[ 2.71828183,  7.3890561 ],
       [20.08553692, 54.59815003]])

Given a list, numpy treats them as np.arrays, it makes an assumption that your list represents a matrix

In [12]:
np.exp(L)

array([[ 2.71828183,  7.3890561 ],
       [20.08553692, 54.59815003]])

matrix multiplication

In [13]:
B = np.array([[1,2,3], [4,5,6]])
B

array([[1, 2, 3],
       [4, 5, 6]])

In [14]:
A.dot(B) # different from A * B, which is element wise products

array([[ 9, 12, 15],
       [19, 26, 33]])

In [15]:
A.dot(B.T)# inner dimensions don't match

ValueError: shapes (2,2) and (3,2) not aligned: 2 (dim 1) != 3 (dim 0)

Some other operations

In [16]:
np.linalg.det(A)

-2.0000000000000004

In [17]:
np.linalg.inv(A)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [18]:
np.linalg.inv(A).dot(A) # we don't get perfect numbers because inverting a matrix is an innaccurate computation in a computer

array([[1.0000000e+00, 4.4408921e-16],
       [0.0000000e+00, 1.0000000e+00]])

In [19]:
np.trace(A) #sum of diag

5

np.diag is an 'overloaded' function

In [20]:
np.diag(A) #we get an array

array([1, 4])

In [21]:
np.diag([1,4]) # what if I call diag on a vector, we get a matrix

array([[1, 0],
       [0, 4]])

eigen values and vectors

In [22]:
λ, V = np.linalg.eig(A)

In [23]:
λ

array([-0.37228132,  5.37228132])

In [24]:
V[:,0]*λ[0], A @ V[:,0]

(array([ 0.30697009, -0.21062466]), array([ 0.30697009, -0.21062466]))

Equality does not close because of precision limitations, we can use np.allclose instead

In [25]:
V[:,0]*λ[0] == A @ V[:,0]

array([ True, False])

In [26]:
np.allclose(V[:,0]*λ[0] , A @ V[:,0])

True

we could have checked all eigen vectors at the same time using matrix notation

In [27]:
V @ np.diag(λ)

array([[ 0.30697009, -2.23472698],
       [-0.21062466, -4.88542751]])

In [28]:
A @ V

array([[ 0.30697009, -2.23472698],
       [-0.21062466, -4.88542751]])

In [29]:
np.allclose(V @ np.diag(λ), A @ V)

True

In [31]:
A, B

(array([[1, 2],
        [3, 4]]),
 array([[1, 2, 3],
        [4, 5, 6]]))

In [32]:
A @ B

array([[ 9, 12, 15],
       [19, 26, 33]])