In [15]:
import numpy as np

In [16]:
L = [1,2,3]

In [17]:
A = np.array([1,2,3])

In [18]:
for e in L:
    print(e)

1
2
3


In [19]:
for e in A:
    print(e)

1
2
3


# arrays are fixed length

In [20]:
L.append(4)


In [21]:
L

[1, 2, 3, 4]

In [22]:
A.append(4)

AttributeError: 'numpy.ndarray' object has no attribute 'append'

# Plus operator is different

In [23]:
L + [5]

[1, 2, 3, 4, 5]

In [24]:
A + np.array([4]) # this is 'broadcasting'

array([5, 6, 7])

Plus operator is intelligent broadcasts when adding a scalar to an array and does vector addition when adding another array

In [25]:
A + np.array([4,5,6])

array([5, 7, 9])

We get an error when adding vectors of different sizes

In [26]:
A + np.array([4,5])

ValueError: operands could not be broadcast together with shapes (3,) (2,) 

# multiplication operator

for array we get vector multiplication and for lists we get repetition. Also for lists L must be a positive integer > 0

In [27]:
2 * A

array([2, 4, 6])

In [28]:
2 * L

[1, 2, 3, 4, 1, 2, 3, 4]

Achieving elementwise operations with Lists

In [29]:
L2 = []

#loop
for e in L:
    L2.append(e+3)
print(L2)

[4, 5, 6, 7]


In [30]:
L2 = [e + 3 for e in L] #comprehension

In [31]:
L2

[4, 5, 6, 7]

In [33]:
L2 = []

for e in L:
    L2.append(e**2)

In [38]:
L2

[1, 4, 9, 16]

Doing it with numpy.array

In [35]:
A**2

array([1, 4, 9])

Functions are most commonly applied elementwise with numpy.arrays

In [36]:
np.sqrt(A)

array([1.        , 1.41421356, 1.73205081])

In [39]:
np.log(A)

array([0.        , 0.69314718, 1.09861229])

In [40]:
np.exp(A)

array([ 2.71828183,  7.3890561 , 20.08553692])

In [41]:
np.tanh(A)

array([0.76159416, 0.96402758, 0.99505475])

Takeaway

numpy.array exists to do math


list looks like an array but works like a generic data structure