In [1]:
import numpy as np

# Generating Data

- WHY?
- sometimes need to generate large matrices that's data has nothing to do with training data e.g. neural network
- generating synthetic data is useful for evaluating model's as we know the ground truth and can see how close we get


In [2]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [3]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [4]:
10 * np.ones((2,3))

array([[10., 10., 10.],
       [10., 10., 10.]])

In [7]:
np.eye(3) #important matrix as it is analogue to the number 1 in linear algebra

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

random numbers to generate arrays. This is used everywhere from markov chain monte carlo

In [8]:
np.random.random()

0.6917327257381277

In [9]:
np.random.random((2,3)) uniform [0,1]

array([[0.47673402, 0.22114021, 0.72237289],
       [0.23135163, 0.34240711, 0.50536405]])

 Always important to ask "what distribution did those random numbers come from?"
 
 -The numbers we get from a uniform dist will be different from those of a normal dist

In [10]:
np.random.randn(2,3) # from standard dist

array([[ 0.03322405, -0.0222693 ,  0.1619147 ],
       [ 0.37183155, -0.4442943 , -0.45745145]])

now we know how to generate random numbers we can calculate some statistics

In [11]:
R = np.random.randn(10000)

In [12]:
R.mean()

0.01459066466026886

In [13]:
R.std()

0.9947967339446148

In [14]:
R.var()

0.9896205418668728

want a 10k by 3 matrix where each element is drawn iid from normal dist


we usually want to mean of each column


In [17]:
R = np.random.randn(10000,3)

In [18]:
R.mean(axis=0)

array([-0.00484389, -0.0029864 ,  0.0004798 ])

In [20]:
R.mean(axis=1).shape

(10000,)


Usually when working with data it is arranged such that each row is an example/observation and each column is a type of measurement

When working with vectors the analogue of the variance is the covariance

Problem! A break from convention in np.cov
shape below shows us that the np.cov by default treats each column as an observation vector. But our rows are the observation vectors!

Solution: use transpose or set rowvar=False


In [22]:
np.cov(R).shape #

(10000, 10000)

In [23]:
np.cov(R.T)

array([[ 1.00087659, -0.01634272, -0.0023654 ],
       [-0.01634272,  1.01329995, -0.0132234 ],
       [-0.0023654 , -0.0132234 ,  1.01492093]])

In [24]:
np.cov(R, rowvar=False)

array([[ 1.00087659, -0.01634272, -0.0023654 ],
       [-0.01634272,  1.01329995, -0.0132234 ],
       [-0.0023654 , -0.0132234 ,  1.01492093]])

In [26]:
np.random.randint(1,10, size=(3,3)) #uniform, [)

array([[7, 1, 2],
       [1, 3, 7],
       [3, 3, 3]])

choice function is useful

inputs

-'a': 1-D array like or int

-'size': tuple

-'replace': boolean
is useful for situations like bootstrapping

-'P': 1-D, array like
allows you to specify the probabilities of selection of eac item. The default is a uniform dist

In [27]:
np.random.choice(10, size=(3,3))

array([[7, 7, 3],
       [9, 6, 6],
       [0, 5, 9]])